/*
Task 1. Create a bank account
Develop a banking system. To do that, first, create an object named “bankAccount”
with the following fields:
    -“bankAccountID”, which is autogenerated
    -“accountNumber”
    -“credentials”, which is an array with a username, password, and pin
    -“balance”, which is an amount of money
    -“createdAt”, which is a date

Task2 Create a user account
Create an object which represents a user account and has the following fields:
    -“bankAccount”, which is an object from task 1
    -“debitCard”, which is a card number
    -“firstName”
    -“lastName”
    -“birthDate”
    -“validID”, which is an array with a type of ID passport or driver’s license and
    the ID number
    -“address”

Task 3. Add functionality to the system
Outside the objects, create functions that enable interaction with a user’s bank
account:
    -“getBankAccountDetails”, which checks if the username and password
    are correct and shows the bank account details
    -“withdrawMoney”, which checks if the username and password are correct and
    enables getting money from the bank account using the account number
    -“depositMoney”, which allows putting money in the bank account using
    the account number
*/

const bankAccount = {
    "bankAccountID" :   [
        {
            "accountNumber" :   "123-4-567-8901-1-1",
             "balance"      :   10000,
             "createdAt"    :   "October 21,2022"
        }, 
    ],
    "credentials":  [
        {
            "username"  :   "Iamgr00t" ,
            "password"  :   "asdhfjgahef",
            "pin"       :   "123456"
        }
    ],   
    "debitCard" :   "1234 1234 1234 1234",
    "firstName" :   "Kurt Ivan",
    "LastName"  :   "Quejada",
    "birthDay"  :   "August 28,2022",
    "validID"   :   [
        {
            "typeOfID"  :   "Drivers License",  //I am not sure how this works because I dont have a valid ID
            "IDnumber"  :   "138417982734189"
        }
    ],
    "address"   :   "123 Main Street, New York, NY 10030" ,// not my real adress

    "getBankAccountDetails" :   function() {
        for(item of this.bankAccountID){
            console.log("account Number "+ item.accountNumber);
            console.log("balance = "+item.balance)
            console.log("created at = "+item.createdAt)
        }
        for(item of this.credentials){ 
            console.log("username = "+item.username)
            console.log("password = "+item.password)
            console.log("Pin = "+item.pin)
        }
    },
    "withdrawMoney" :  function(username, password, amount){
        for (item of this.credentials){
            if ((username === item.username)&&(password=== item.password)) {
                console.log("You have withdraw "+amount)
            }else {
                console.log("Your username and password does not match")
            }
            for(item of this.bankAccountID){
                item.balance -= amount
                console.log("Your Balance is now "+item.balance+". Account Number Used is "+ item.accountNumber)
            }
        }
      
        
    },
    "depositMoney"  :   function(accountNumber, depositAmount){
        for(item of this.bankAccountID){
            if(accountNumber === item.accountNumber){
                console.log("You have send "+ depositAmount + " worth of money to "+ item.accountNumber)
            }else {
                console.log("This account number does not exist")
            }
        }
    }

};

    




bankAccount.getBankAccountDetails()
bankAccount.withdrawMoney("Iamgr00t","asdhfjgahef",123)
bankAccount.depositMoney("123-4-567-8901-1-1", 1000)
